<?php $sliderpreviewId= $this->getRequest()->getParam('sliderpreview_id') ?>

<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::css/slider'.$sliderpreviewId.'.css')?>">
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::css/evolution.css')?>">
<?php $sliderEvolutionTransition = $this->getSliderEvolutionTransitionArray(); ?>
<script type="text/javascript">
    require(['jquery','magestore/evolutionslider'], function($) {
        $(document).ready(function($) {
            $(".slider").slideshow({
                width: 550,
                height: 325,
                transition: <?php echo json_encode($sliderEvolutionTransition[$sliderpreviewId]); ?>
            });
        });
    });
</script>
 <div class="slider" style="margin:auto;">
     <div>
         <img style="width:550px; height: 325px;" src="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::images/demo/kitchen_adventurer_cheesecake_brownie.jpg')?>"/>
     </div>

     <div>
         <img style="width:550px; height: 325px;" src="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::images/demo/kitchen_adventurer_lemon.jpg') ?>"/>
     </div>

     <div>
         <img style="width:550px; height: 325px;" src="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::images/demo/kitchen_adventurer_donut.jpg') ?>"/>
     </div>
     <div>
         <img style="width:550px; height: 325px;" src="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::images/demo/kitchen_adventurer_caramel.jpg') ?>"/>
     </div>
 </div>
