<script type="text/javascript">
//<![CDATA[
    require(['prototype'], function() {
    	reportGridJsObject.doFilter = function (){
            var filters = $$('#'+this.containerId+' .filter input', '#'+this.containerId+' .filter select', '#magestore-bannerslider-formdate input', '#magestore-bannerslider-todate input');
            var elements = [];
            for(var i in filters){
                if(filters[i].value && filters[i].value.length) elements.push(filters[i]);
            }
            if (!this.doFilterCallback || (this.doFilterCallback && this.doFilterCallback())) {
                this.reload(this.addVarToUrl(this.filterVar, encode_base64(Form.serializeElements(elements))));
            }
        }
    });
//]]>
</script>
